apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
    listen 80;

    # 🔥 API FIRST (priority)
    location /api/ {
        rewrite ^/api/(.*) /$1 break;
        proxy_pass http://backend-api.dev.svc.cluster.local:8080;
    }

    # Frontend
    location / {
        proxy_pass http://remix-frontend-service.dev.svc.cluster.local:80;
    }
